version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.5.1
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"   # HTTP interface (for query via curl/DBeaver) # HTTP (web / API) # Port HTTP to connect from Grafana / UI
      - "9000:9000"   # Native protocol (for client apps), example from Airflow / Python
      - "9004:9004"   # MySQL protocol (optional, can connect via MySQL client)
    volumes:
      - ./data:/var/lib/clickhouse        # data persisten
      - ./logs:/var/log/clickhouse-server # logs persisten
      - ./config/timezone.xml:/etc/clickhouse-server/config.d/timezone.xml
      - ./config/users.xml:/etc/clickhouse-server/users.d/users.xml
    environment:
      TZ: Asia/Singapore
      CLICKHOUSE_DB: warehouse
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: secret123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    mem_limit: 3g          # limit RAM maximum 3GB
    cpus: "2"              # limit CPU 2 core